name: Test

on:
  - push
  - pull_request

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust-version: [1.31.0, stable, nightly]
        mode: [native]
        include:
          - os: macos-latest
            rust-version: stable
          - os: windows-latest
            rust-version: stable
            build_arg: "--features bundled-sqlite"
    runs-on: ${{ matrix.os }}
    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Rust ${{ matrix.rust-version }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust-version }}
          override: true
      - name: Build
        run: cargo build --verbose ${{ matrix.build_arg }}
      - name: Run tests
        run: cargo test --verbose ${{ matrix.build_arg }}
